### ISSUE TITLE
Re-add unknown file size support.

### ISSUE THREAD

**Issue by catjacks38** [catjacks38/ImageSteganography#12]
@Reep236 when you made changes to the channelToData and LSBDecode functions it broke support for unknown file sizes. This change makes it so you can only use the autoDecode method to decode the data from images. Please add back a condition that supports unknown file size when the file size inputted is less than or equal to zero.

**Comment by Reep236** [comment]
Didn't realize fileSize wasn't being read for direct methods
#13 includes fix

**Comment by catjacks38** [comment]
Seems like it worked.
