### ISSUE TITLE
LSBEncode & LSBDecode Speed Improvements

### ISSUE THREAD

**Issue by Reep236** [catjacks38/ImageSteganography#2]
LSBEncode/Decode functions are currently quite slow and costly. 

Utilizing more array operators may be able to help with this, reducing the cost of iterations.

**Comment by catjacks38** [comment]
Makes sense. I will try to improve efficiency of LSBEncode and LSBDecode functions.

**Comment by catjacks38** [comment]
Wait never mind. You are gonna fix that apparently. ¯\_(ツ)_/¯

**Comment by Reep236** [comment]
Major improvements from #8; tagging as Long Term

**Comment by catjacks38** [comment]
I'm confused why this issue is still opened. I doubt we can get the speed any faster, because we're using numpy function.

**Comment by catjacks38** [comment]
Yeah, I think I'm just going to close this issue, and we can reopen it if we find any more ways to improve performance of D2C and LSB.
