### ISSUE TITLE
Improved Comments/Documentation

### ISSUE THREAD

**Issue by Reep236** [catjacks38/ImageSteganography#4]
Majority of repo is lacking in terms of comments

**Comment by catjacks38** [comment]
I can do this.

**Comment by catjacks38** [comment]
@Reep236 could you write the comment documentation for the channelToData and dataToChannel functions? Just because you wrote them, and I don't want to document them wrong. I can do the rest of the scripts and functions though.

**Comment by catjacks38** [comment]
Alright. Seems like the comment documentation is done. I guess it is time to close this issue.
