### ISSUE TITLE
Auto-Select Optimal LSBMode

### ISSUE THREAD

**Issue by Reep236** [catjacks38/ImageSteganography#5]
LSBMode should be the lowest possible for the image. Mode should be defaulted as such unless otherwise specified by the user. 

This can be lumped into filling out images with data as done in dataToChannel. A fully noisy image is less conspicuous than a partially noisy one

**Comment by catjacks38** [comment]
#16 is merged with main branch now. Closing issue.

**Comment by Reep236** [comment]
This can be done for decode when a fileSize argument is provided. With warning, of course, in case the optimal mode was not used initially.

**Comment by Reep236** [comment]
@catjacks38 , you can reassign to me if desired

**Comment by catjacks38** [comment]
I mean I don't see the point of doing that, but if you want to do it, you can.
